["DEL"]
prototype = "DEL x: ..."
short = "Delay command by `x` ms"
description = """
Delay the command following the colon by `x` ms by placing it into a buffer. 
The buffer can hold up to 16 commands. If the buffer is full, additional commands
will be discarded.
"""
["DEL.CLR"]
prototype = "DEL.CLR"
short = "Clear the delay buffer"
description = """
Clear the delay buffer, cancelling the pending commands.
"""
["DEL.X"]
prototype = "DEL.X x delay_time: ..."
short = "Delay `x` commands at `delay_time` ms intervals"
description = """
Delay the command following the colon `x` times at intervals of `delay_time` ms by placing it into a buffer. 
The buffer can hold up to 16 commands. If the buffer is full, additional commands
will be discarded.
"""
["DEL.R"]
prototype = "DEL.R x delay_time: ..."
short = "Trigger the command following the colon once immediately, and delay `x - 1` commands at `delay_time` ms intervals"
description = """
Delay the command following the colon once immediately, and `x - 1` times at intervals of `delay_time` ms by placing it into a buffer. 
The buffer can hold up to 16 commands. If the buffer is full, additional commands
will be discarded.
"""
["DEL.G"]
prototype = "DEL.G x delay_time num denom: ..."
short = "Trigger the command once immediately and `x - 1` times at ms intervals of `delay_time * (num/denom)^n` where n ranges from 0 to `x - 1`."
description = """
Trigger the command once immediately and `x - 1` times at ms intervals of `delay_time * (num/denom)^n` where n ranges from 0 to `x - 1` by placing it into a buffer. 
The buffer can hold up to 16 commands. If the buffer is full, additional commands
will be discarded.
"""